import { Item } from './types';

export const ITEMS: Record<string, Item> = {
  sword: {
    id: 'sword',
    name: 'Sword',
    type: 'weapon',
    attackBonus: 4,
    defenseBonus: 0,
    hpRestore: 0,
    description: '+4 Attack',
  },
  dagger: {
    id: 'dagger',
    name: 'Dagger',
    type: 'weapon',
    attackBonus: 2,
    defenseBonus: 0,
    hpRestore: 0,
    description: '+2 Attack',
  },
  mace: {
    id: 'mace',
    name: 'Mace',
    type: 'weapon',
    attackBonus: 3,
    defenseBonus: 0,
    hpRestore: 0,
    description: '+3 Attack',
  },
  shield: {
    id: 'shield',
    name: 'Shield',
    type: 'armor',
    attackBonus: 0,
    defenseBonus: 3,
    hpRestore: 0,
    description: '+3 Defense',
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    type: 'armor',
    attackBonus: 0,
    defenseBonus: 2,
    hpRestore: 0,
    description: '+2 Defense',
  },
  potion: {
    id: 'potion',
    name: 'Health Potion',
    type: 'consumable',
    attackBonus: 0,
    defenseBonus: 0,
    hpRestore: 10,
    description: 'Restore 10 HP',
  },
  key: {
    id: 'key',
    name: 'Iron Key',
    type: 'key',
    attackBonus: 0,
    defenseBonus: 0,
    hpRestore: 0,
    description: 'Opens locked chests',
  },
};
