import { Item } from './types';

export const ITEMS: Record<string, Item> = {
  sword: {
    id: 'sword',
    name: 'Sword',
    type: 'weapon',
    attackBonus: 4,
    defenseBonus: 0,
    dexterityBonus: 0,
    camouflageBonus: 0,
    hpRestore: 0,
    description: '+4 Attack',
  },
  dagger: {
    id: 'dagger',
    name: 'Dagger',
    type: 'weapon',
    attackBonus: 2,
    defenseBonus: 0,
    dexterityBonus: 1,
    camouflageBonus: 0,
    hpRestore: 0,
    description: '+2 Attack, +1 Dexterity',
  },
  mace: {
    id: 'mace',
    name: 'Mace',
    type: 'weapon',
    attackBonus: 3,
    defenseBonus: 0,
    dexterityBonus: 0,
    camouflageBonus: 0,
    hpRestore: 0,
    description: '+3 Attack',
  },
  shield: {
    id: 'shield',
    name: 'Shield',
    type: 'armor',
    attackBonus: 0,
    defenseBonus: 3,
    dexterityBonus: 0,
    camouflageBonus: 0,
    hpRestore: 0,
    description: '+3 Defense',
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    type: 'armor',
    attackBonus: 0,
    defenseBonus: 2,
    dexterityBonus: 0,
    camouflageBonus: 0,
    hpRestore: 0,
    description: '+2 Defense',
  },
  boots_of_silence: {
    id: 'boots_of_silence',
    name: 'Boots of Silence',
    type: 'armor',
    attackBonus: 0,
    defenseBonus: 0,
    dexterityBonus: 3,
    camouflageBonus: 0,
    hpRestore: 0,
    description: '+3 Dexterity (Sneak)',
  },
  cloak_of_shadows: {
    id: 'cloak_of_shadows',
    name: 'Cloak of Shadows',
    type: 'armor',
    attackBonus: 0,
    defenseBonus: 1,
    dexterityBonus: 0,
    camouflageBonus: 3,
    hpRestore: 0,
    description: '+3 Camouflage, +1 Defense',
  },
  potion: {
    id: 'potion',
    name: 'Health Potion',
    type: 'consumable',
    attackBonus: 0,
    defenseBonus: 0,
    dexterityBonus: 0,
    camouflageBonus: 0,
    hpRestore: 10,
    description: 'Restore 10 HP',
  },
  scroll_of_concealment: {
    id: 'scroll_of_concealment',
    name: 'Scroll of Concealment',
    type: 'consumable',
    attackBonus: 0,
    defenseBonus: 0,
    dexterityBonus: 0,
    camouflageBonus: 5,
    hpRestore: 0,
    description: '+5 Camouflage (permanent)',
  },
  key: {
    id: 'key',
    name: 'Iron Key',
    type: 'key',
    attackBonus: 0,
    defenseBonus: 0,
    dexterityBonus: 0,
    camouflageBonus: 0,
    hpRestore: 0,
    description: 'Opens locked chests',
  },
};
